// ============================================================
// PURPOSE:
//   The transposition table used by DPSolver. Stores the
//   minimax score of board states that have already been
//   computed so they are never recomputed from scratch.
//
// RESPONSIBILITIES:
//   - Store (board key → minimax score) pairs
//   - Answer lookups: "have we seen this board before?"
//   - If yes, return the stored score instantly (cache hit)
//   - If no, signal a cache miss so the solver recurses normally
//   - Store new results after computing them
//
// HOW IT FITS IN THE PROJECT:
//   DPSolver calls Cache::get() at the top of every minimax call.
//   If it gets a hit, it returns immediately — zero recursion.
//   If it misses, it recurses as normal, then calls Cache::set()
//   to store the result before returning.
//   BruteForceSolver never touches Cache at all.
//
// WHY THIS WORKS (the DP argument):
//   Different move sequences can reach the same board state.
//   Example: X→(0,0) then X→(0,2) reaches the same board as
//            X→(0,2) then X→(0,0).
//   Without cache: the entire subtree is recomputed every time.
//   With cache: computed once, looked up instantly every other time.
//   This converts exponential recomputation into O(1) lookups.
//
// KEY FORMAT:
//   The key is a string generated by Board::getKey().
//   Example: "X_XOO____" for a 3x3 board.
//   It encodes ONLY the board configuration — not the move
//   sequence that led there. This is what makes DP valid here.
//
// IMPORTANT NOTES FOR TEAMMATES:
//   - Cache is owned by DPSolver — one Cache object per solver
//   - clear() must be called between benchmark runs to avoid
//     stale results from a previous board size or depth
//   - optional<int> is used for get() so we can clearly
//     distinguish a cache hit (has value) from a miss (nullopt)
// ============================================================

#pragma once
#include <unordered_map>
#include <string>
#include <optional>

using namespace std;

class Cache {
public:
    // ----------------------------------------------------------
    // get(key)
    // Looks up a board key in the cache.
    // Returns the stored score if found (cache hit).
    // Returns nullopt if not found (cache miss).
    //
    // Usage in DPSolver:
    //   auto result = cache.get(board.getKey());
    //   if (result.has_value()) return result.value(); // hit
    //   // otherwise recurse normally...
    // ----------------------------------------------------------
    optional<int> get(const string& key) const;

    // ----------------------------------------------------------
    // set(key, score)
    // Stores a computed minimax score in the cache.
    // Called by DPSolver AFTER recursing, before returning.
    // ----------------------------------------------------------
    void set(const string& key, int score);

    // ----------------------------------------------------------
    // clear()
    // Removes all entries from the cache.
    // Must be called between benchmark runs (different N or depth)
    // to avoid incorrect cache hits from a previous run.
    // ----------------------------------------------------------
    void clear();

    // ----------------------------------------------------------
    // size()
    // Returns how many unique board states are stored.
    // Useful for reporting "unique states explored" in the report.
    // ----------------------------------------------------------
    int size() const;

private:
    // The actual hash map: board string → minimax score
    // unordered_map gives O(1) average lookup and insert
    unordered_map<string, int> table;
};